# coding=utf-8
"""delayed_tasks settings"""
import os

DELAYED_TASKS_STORE_TASK_ETA_MINUTES = int(os.getenv('DELAYED_TASKS_STORE_TASK_ETA_MINUTES', 60)),
DELAYED_TASKS_SCHEDULE_TASK_AHEAD_ETA_MINUTES = int(os.getenv('DELAYED_TASKS_SCHEDULE_TASK_AHEAD_ETA_MINUTES', 10))
DELAYED_TASKS_SCHEDULE_TASKS_INTERVAL_MINUTES = int(os.getenv('DELAYED_TASKSrSCHEDULE_TASKS_INTERVAL_MINUTES', 2))
